### ISSUE TITLE
Exception has been thrown by target of invocation

### ISSUE THREAD

**Issue by pboyd04** [jmichelp/sdrsharp-bladerf#1]
i get an error dialog about the SDRSharp.BladeRF library when loading SDRSharp.

BladeRF-CLI sees everything ok:
bladeRF> probe

  Backend:        CyUSB driver
  Serial:         611e5838b88308291deab7b99bb363cd
  USB Bus:        0
  USB Address:    12

bladeRF> info

  Serial #:                 611e5838b88308291deab7b99bb363cd
  VCTCXO DAC calibration:   0x9cd3
  FPGA size:                40 KLE
  FPGA loaded:              yes
  USB bus:                  0
  USB address:              12
  USB speed:                SuperSpeed
  Backend:                  Cypress driver
  Instance:                 0

bladeRF> version

  bladeRF-cli version:        1.1.2
  libbladeRF version:         1.2.1

  Firmware version:           1.8.0
  FPGA version:               0.1.2

**Comment by jmichelp** [comment]
Could you detail the message you are seeing?
Otherwise it will be pretty hard to reproduce or understand what's happening and therefore fixing it.

**Comment by pboyd04** [comment]
Unfortunately, that's all it says... I don't know how to enable any further logging...

**Comment by jmichelp** [comment]
In C# exceptions you should have a button in the dialog box to show details about the exception. This will give me details on where on the code this is happening.

Cypress backend should just work fine (this is the backend I am using too).
Have you copied all DLL files from the release ZIP file in the SDRSharp directory?

**Comment by pboyd04** [comment]
Turns out I put the 64-bit native dll's in the folder instead of the the 32-bit. That results in this mystery exception with no more details.

**Comment by jmichelp** [comment]
Super. Thank you for the update and for drilling down the issue as I wasn't able to reproduce.
