### ISSUE TITLE
doesn't work Correct IQ in SDR# 1443

### ISSUE THREAD

**Issue by eroyzman** [jmichelp/sdrsharp-bladerf#11]
Hi,

Have some problem with Correct IQ function in SDR# v.1443. When i chek this one function no any respons from central peak (DC offset), this peak stays at max. everytime. 

I can't understand, or this problem solves from SDR# side, or from your side.

Use bladeRfx40 with XB200, Win 7 Pro, SDR# 1443, .Net 4.6.1

**Comment by jmichelp** [comment]
Could you try with the latest push and tell me if the issue is still present?

**Comment by jmichelp** [comment]
Closing as there's no feedback
