### ISSUE TITLE
SDR# does not recognize bladeRF for source

### ISSUE THREAD

**Issue by GlenNicholls** [jmichelp/sdrsharp-bladerf#12]
I went through your walkthrough to add bladeRF compatibility in SDR#. However, when I walk through all of the steps, including reinstalling the USB driver for the bladeRF through zadig.exe, SDR# still does not allow me to select the bladeRF as an option. For reference, I have tried both the install files for x86 and x64 with no luck, including uninstalling and reinstalling. I am also on a Windows 10 machine. Does anyone know what the issue might be?

**Comment by GlenNicholls** [comment]
I also forgot to mention (not sure how this could cause issues) that I am autoloading the latest firmware. I am also able to use the bladeRF through bladeRF-cli and my device manager recognizes the device attached to the USB 3.0 port.

**Comment by jmichelp** [comment]
I'm a bit busy at the moment but I will have a look as soon as possible. I haven't updated SDR# on my computer for quite a while and maybe they changed some API for the plugins.

I guess you're running the latest version of SDR# which is r1572 at the moment, right?

**Comment by GlenNicholls** [comment]
Yeah, I'm running the latest version of SDR#. What is the most recent version of SDR# that supports bladeRF?

**Comment by jmichelp** [comment]
r1446 works for me. I have to check but it could something very simple to fix such as compiling in 64bit mode. Maybe they updated their binary.

**Comment by spacepony** [comment]
Having the same recognition issue with r1577 (win10/x64), tried digging up r1446 but couldn't find it...

**Comment by jmichelp** [comment]
I pushed a new binary which hopefully should solve the issue. I don't have the time at the moment to finish the redesign, push new feature or test the new DLL but at least it appears on the GUI with the latest version of SDR# :)
Just download the file `Release\SDRSharp.BladerRF.dll` and test

**Comment by peseta3** [comment]
Hallo Together,

I have a Problem with My BladeRF-40 and Win 10 with SDRSharp

> the source SRSharp.BladeRF.BladeRFIO is not ready

The source fild is gray...
![sdrsharp1](https://user-images.githubusercontent.com/24300824/36207126-1f637090-1195-11e8-91a4-7c88e4a37b88.jpg)
![sdrsharp2](https://user-images.githubusercontent.com/24300824/36207129-227c006c-1195-11e8-8b87-062357f9d9f9.jpg)

**Comment by jmichelp** [comment]
Thanks for reporting. Just to rule out an obvious cause: if you use the tools from bladeRF (e.g. bladerf-cli.exe) are you able to interact with the bladeRF or not?
At the moment I'm pretty busy but I will try to replicate and push a fix as soon as I can if this is required.

**Comment by jmichelp** [comment]
bladerf-cli.exe can open the device while my wrapper cannot. Something has probably changed in bladeRF API or in the way SDRSharp calls the wrapper. I will investigate and do my best to quickly fix this issue.

**Comment by jmichelp** [comment]
Took me a while but I identified the problem. It's a bug on Nuand side when using libusb backend for BladeRF.

I compiled a version of the tools and the library with the fix so that people can start using it and I will push the fix upstream.

**Comment by spacepony** [comment]
Confirming that I can now see/select the board! Just stuck on a new error (see issue #14). Almost there! :-)

**Comment by leVignesh** [comment]
@jmichelp I Have been facing the problem that Blade Rf is not in the source list. Would you please provide the link for sdr sharp software that supports Blade Rf

**Comment by R0aDt0OSCP** [comment]
> Hallo Together,
> 
> I have a Problem with My BladeRF-40 and Win 10 with SDRSharp
> 
> > the source SRSharp.BladeRF.BladeRFIO is not ready

Any solution facing similar issues

**Comment by R0aDt0OSCP** [comment]
![Image](https://github.com/user-attachments/assets/85330826-d739-4bfe-bf0d-e1affbece08d)
