### ISSUE TITLE
libbladerf is too old

### ISSUE THREAD

**Issue by cn0xroot** [jmichelp/sdrsharp-bladerf#13]
when i run sdr-sharp with bladerf, error:
libbladerf is too old. got 1.5.1-git-ba561a4 and expecting at least v1.7

**Comment by cn0xroot** [comment]
fix it through update LibBladeRF to 1.7.2 version.
[ https://github.com/cn0xroot/sdrsharp-bladerf]( https://github.com/cn0xroot/sdrsharp-bladerf)

**Comment by mglass1646** [comment]
I have the same problem but when using v1.72 the BladeRF no longer shows up as a device in SDR#.

**Comment by jmichelp** [comment]
I just compiled libbladerf 1.9 from git and I recompiled the assembly against SDRSharp r1660.
If the bladeRF still doesn't appear in SDR# this means that they changed some API in SDR# that I will have to implement. But to do so I need my unit

**Comment by jmichelp** [comment]
Tried today and BladeRF is seen with the pre-compiled library that I provide in the repository so I'll close this bug.

The fact that the bladeRF cannot be opened is tracked in issue #12
