### ISSUE TITLE
bladerf_set_loopback() error. An unexpected error occurred

### ISSUE THREAD

**Issue by spacepony** [jmichelp/sdrsharp-bladerf#14]
This is essentially the same error as an already closed bug, so feel free to collapse if it makes sense. 

Windows 10, x115+xb200 w/latest firmware, latest FPGA, latest sdrsharp-bladerf, latest sdr# (v1666)

Can select/see the board, but when attempting to start SDR#, I get the following: 

"bladerf_set_loopback() error. An unexpected error occurred"

Please let me know if I can provide any additional details/troubleshooting/etc.

**Comment by jmichelp** [comment]
That's weird. Everything works on my side without error.
Plus, this error happens during the configuration of the bladeRF. That's going to be hard for me to reproduce. Does the bladeRF work when you're running the test programs or using it through the CLI? The init/config phases should be very similar.

**Comment by jmichelp** [comment]
Closing the bug as I wasn't able to reproduce

**Comment by bretesq** [comment]
I'm receiving the same error message as @spacepony mentioned originally. I've tried recompiling from source and attached debugger. It appears to be throwing on line 572 in BladeRFDevice.cs

``
if (fp_size == bladerf_fpga_size.BLADERF_FPGA_40KLE || fp_size == bladerf_fpga_size.BLADERF_FPGA_115KLE) {
                if ((error = NativeMethods.bladerf_set_loopback(_dev, bladerf_loopback.BLADERF_LB_NONE)) != 0)
                    throw new ApplicationException(String.Format("bladerf_set_loopback() error. {0}", NativeMethods.bladerf_strerror(error)));
``

**Comment by sunw4r** [comment]
@bretesq @spacepony have you guys solved it?
