### ISSUE TITLE
Inverted mouse frequency click and slide

### ISSUE THREAD

**Issue by fabiencomte** [jmichelp/sdrsharp-bladerf#6]
Hello,

When I slide frequencies on FFT view directly with the mouse (left click maintened and mouse move), the horizontal move is inverted.

**Comment by jmichelp** [comment]
Hi,

This plugin is simply interfacing the bladeRF with SDRSharp. It's doesn't deal with the user interface beside the bladeRF configuration panel. So, from the plugin's point of view, it's just receiving an API call with an absolute value which is the desired target frequency.

**Comment by jmichelp** [comment]
Ok, my bad. I just saw that the SDRsharp authors swapped I and Q samples which explains why the frequency is going the other way around.

I will fix it in the next version but right now I am working on another feature. In the meantime, the workaround is to check the box "Swap I & Q" to get the correct values.

**Comment by fabiencomte** [comment]
Thank you.

**Comment by jmichelp** [comment]
Should be fixed with the latest pre-compiled DLL from GitHub that includes commit 5490d183b7b57891339110117d5a954512b809a9.
Otherwise re-open the bug.
