### ISSUE TITLE
bladerf_set_loopback() error

### ISSUE THREAD

**Issue by fabiencomte** [jmichelp/sdrsharp-bladerf#8]
Hello,
When I try to use my BladeRF (last version of soft, FW and FPGA) with SDR# (last version) i get this message "bladerf_set_loopback() error. An unexpected error occured".

**Comment by jmichelp** [comment]
Hi,
Thanks for reporting. I have been pretty busy and haven't been able to keep up with the changes pushed to the main library. Some API calls may have changed. I will look at that.

To assess the priority of this bug, Is it completely preventing the usage of BladeRF with SDR# or not?

**Comment by jmichelp** [comment]
Well, I finally got a bit of time to look at it tonight.
Please, try the latest pre-compiled DLL provided in the GitHub repository. I had no issue on my setup with it using freshly compiled libbladerf compiled from GitHub, latest FW + FPGA and SDR# r1443.

**Comment by fabiencomte** [comment]
It fixed issue. Thank you a lot.

**Comment by jmichelp** [comment]
Great!
Hopefully I will find some time around Easter to finish all the changes I have in mind :)
